version: "3.9"

services:
  db:
    image: postgres:17
    container_name: trabalho-final-gc-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: trabalho-final-db
    ports:
      - "5432:5432"
    volumes:
      - trabalho-final-gc-db:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: trabalho-final-gc-server
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://root:root@db:5432/trabalho-final-db
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: trabalho-final-gc-frontend
    depends_on:
      - server
    ports:
      - "3001:3000"

volumes:
  trabalho-final-gc-db:
